defaults:
  - path
  - _self_
  - dataset: om # om / um
  - model: dcl # cnn, lstm, dcl, dcl-sa, resnet-l-sa, transformer, cnn-ae
#  - override hydra/job_logging: console_and_file
  
hydra:
  run:
    dir: ${path.log.rootdir}
  job:
    chdir: true

issue: "I03"
ex: "ex-d00"
debug: false
seed: 0 # random seed
k8s: false

metadata: 
  approach: 'dl'
  task: 'loiocv'

train:
  cuda: 0 
  train_val_split: true
  train_data_ratio: 0.8 # validation data used only for early stopping
  shuffle: true
  train_balanced: true # use balanced_train_loader
  data_augmentation: true
  manifold_mixup: false
  mixup_alpha: 0.2
  mixup_targets_argmax: false
  batch_size: 128
  n_epoch: 100 # 100, 150, 200
  min_epoch: 70
  patience: 10 # early stopping parameter
  optimizer: "Adam" # "Adam", "SGD"
  lr: 1e-3
  weight_decay: 1e-4 # 1e-4, 1e-5
  scheduler: "CosineLR" # "CosineLR", "Plataeu"
  criterion: "CE"       # "CE": Cross Entropy Loss

sub0: "${issue}/${ex}"
sub1: "${dataset.species}-${dataset.window_size}"
sub2: "${model.model_name}"
sub3: "" # override sub3 when running models using k8s
sub4: "seed${seed}"
sub5: "${dataset.test_animal_id}"
sub_root_dir: "${sub0}/${sub1}/${sub2}/${sub3}/${sub4}/${sub5}"