# DCL with Mixup after LSTM layer version
model_name: "dcl-v3"
kernel_size: 5
num_conv_layers: 4
num_conv_filters: 128
num_lstm_hidden_units: 128
num_lstm_layers: 1
bidirectional_lstm: false
out_layer_type: "flatten-linear-2" # "1-by-1-conv" or "flatten-linear" or "flatten-linear-2"
out_dropout_rate: 0.0