model_name: "transformer"
dim: 128
depth: 4
heads: 4 # 4, 8
mlp_dim: 64 # 64, 128, 256
dropout: 0.1 # 0.1, 0.2, 0.5
out_layer_type: "flatten-linear-2" # "1-by-1-conv" or "flatten-linear" or "flatten-linear-2"
out_dropout_rate: 0.0